import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { CheckCircle2, ClipboardCheck, Database, FolderArchive, ShieldCheck, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Verification = { placeId: string; name: string; region: string; status: "draft" | "verified" | "needs-review"; sourceUrl: string | null; verifiedAt: Date | null; internalNote: string | null; updatedAt: Date | null };
type ManagedPlan = { id: number; title: string; region: string; scheduledFor: Date | null; budgetLimit: number | null; isShared: boolean; isArchived: boolean; adminStatus: "active" | "review" | "archived"; adminNote: string | null; updatedAt: Date; ownerName: string | null; ownerEmail: string | null };

export default function Admin() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: user?.role === "admin" });
  const verifications = trpc.admin.verifications.useQuery(undefined, { enabled: user?.role === "admin" });
  const plans = trpc.admin.plans.useQuery(undefined, { enabled: user?.role === "admin" });
  const update = trpc.admin.updateVerification.useMutation({ onSuccess: () => { utils.admin.verifications.invalidate(); utils.admin.overview.invalidate(); toast.success("검증 레코드를 저장했어요."); } });
  const updatePlan = trpc.admin.updatePlan.useMutation({ onSuccess: () => { utils.admin.plans.invalidate(); toast.success("플랜 운영 상태를 저장했어요."); } });
  useEffect(() => {
    if (plans.data && window.location.hash === "#plan-operations") document.getElementById("plan-operations")?.scrollIntoView({ block: "start" });
  }, [plans.data]);
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f7f3ed] text-sm text-[#706156]">운영 화면을 준비하는 중입니다.</div>;
  if (user?.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#f7f3ed] px-5 text-center"><div><ShieldCheck className="mx-auto h-8 w-8 text-[#a45c39]" /><h1 className="mt-4 font-serif text-3xl font-semibold">운영자 권한이 필요합니다.</h1><p className="mt-2 text-sm text-[#706257]">이 화면은 장소 정보의 출처와 검증 상태를 관리하는 운영 도구입니다.</p></div></div>;
  const records = verifications.data ?? [];
  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-7 p-2 sm:p-6"><header><p className="text-xs font-bold tracking-[0.17em] text-[#a55c39]">ONGIHAENG OPERATIONS</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">장소와 여행 데이터 운영</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6e6258]">공식 출처, 검증일, 내부 확인 메모와 사용자 플랜의 운영 상태를 관리합니다.</p></header><div className="grid gap-4 md:grid-cols-3"><Metric icon={<Users />} label="사용자" value={overview.data?.users ?? 0} /><Metric icon={<ClipboardCheck />} label="여행 플랜" value={overview.data?.plans ?? 0} /><Metric icon={<Database />} label="운영 검증 레코드" value={overview.data?.verificationRecords ?? 0} /></div><section id="place-verifications" className="scroll-mt-6 rounded-[1.5rem] border border-[#e2d9d0] bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#4f765a]" /><p className="text-xs font-bold tracking-widest text-[#526d58]">PLACE VERIFICATION QUEUE</p></div><h2 className="mt-2 font-serif text-2xl font-semibold">장소 출처와 검증 상태</h2><div className="mt-5 space-y-4">{records.map(record => <VerificationEditor key={record.placeId} record={record} onSave={input => update.mutate(input)} saving={update.isPending} />)}</div></section><section id="plan-operations" className="scroll-mt-6 rounded-[1.5rem] border border-[#e2d9d0] bg-white p-5"><div className="flex items-center gap-2"><FolderArchive className="h-4 w-4 text-[#a55c39]" /><p className="text-xs font-bold tracking-widest text-[#a55c39]">TRIP PLAN OPERATIONS</p></div><h2 className="mt-2 font-serif text-2xl font-semibold">사용자 플랜 운영</h2><p className="mt-2 text-sm text-[#706257]">아카이브 상태는 공개 공유를 자동 해제합니다. 사용자의 여행 내용은 수정하지 않고 운영 상태와 내부 메모만 관리합니다.</p><div className="mt-5 space-y-4">{(plans.data ?? []).map(plan => <PlanOperator key={plan.id} plan={plan} onSave={input => updatePlan.mutate(input)} saving={updatePlan.isPending} />)}{plans.data?.length === 0 && <p className="rounded-xl bg-[#fbf7f1] p-5 text-sm text-[#74665b]">아직 운영할 여행 플랜이 없습니다.</p>}</div></section></div></DashboardLayout>;
}

function VerificationEditor({ record, onSave, saving }: { record: Verification; onSave: (input: { placeId: string; status: Verification["status"]; sourceUrl: string | null; verifiedAt: Date | null; internalNote: string | null }) => void; saving: boolean }) {
  const [status, setStatus] = useState(record.status);
  const [sourceUrl, setSourceUrl] = useState(record.sourceUrl ?? "");
  const [verifiedAt, setVerifiedAt] = useState(record.verifiedAt ? new Date(record.verifiedAt).toISOString().slice(0, 10) : "");
  const [note, setNote] = useState(record.internalNote ?? "");
  return <article className="rounded-2xl border border-[#e8dfd6] bg-[#fdfaf6] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-serif text-xl font-semibold">{record.name}</p><p className="mt-1 text-xs text-[#786a5f]">{record.region} · {record.updatedAt ? `최근 저장 ${new Date(record.updatedAt).toLocaleDateString("ko-KR")}` : "초기 카탈로그 상태"}</p></div><select aria-label={`${record.name} 검증 상태`} value={status} onChange={event => setStatus(event.target.value as Verification["status"])} className="h-9 rounded-lg border border-[#dfd2c5] bg-white px-3 text-xs font-bold text-[#725d4d]"><option value="verified">공식 확인</option><option value="needs-review">재검토 필요</option><option value="draft">초안</option></select></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_145px]"><input aria-label={`${record.name} 출처 URL`} value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} placeholder="https:// 공식 출처 주소" className="h-10 rounded-lg border border-[#e3d9cf] bg-white px-3 text-xs outline-none focus:border-[#a65e3b]" /><input aria-label={`${record.name} 검증일`} type="date" value={verifiedAt} onChange={event => setVerifiedAt(event.target.value)} className="h-10 rounded-lg border border-[#e3d9cf] bg-white px-3 text-xs outline-none focus:border-[#a65e3b]" /></div><textarea aria-label={`${record.name} 내부 메모`} value={note} onChange={event => setNote(event.target.value)} placeholder="운영자 확인 메모 (사용자에게 공개되지 않습니다)" className="mt-3 min-h-20 w-full rounded-lg border border-[#e3d9cf] bg-white p-3 text-xs leading-5 outline-none focus:border-[#a65e3b]" /><div className="mt-3 flex justify-end"><Button size="sm" disabled={saving || (sourceUrl.length > 0 && !sourceUrl.startsWith("https://"))} onClick={() => onSave({ placeId: record.placeId, status, sourceUrl: sourceUrl || null, verifiedAt: verifiedAt ? new Date(`${verifiedAt}T00:00:00.000Z`) : null, internalNote: note || null })} className="rounded-lg bg-[#2d453a] text-xs text-white hover:bg-[#22372e]">검증 레코드 저장</Button></div></article>;
}

function PlanOperator({ plan, onSave, saving }: { plan: ManagedPlan; onSave: (input: { planId: number; adminStatus: ManagedPlan["adminStatus"]; adminNote: string | null; isShared: boolean }) => void; saving: boolean }) {
  const [status, setStatus] = useState(plan.adminStatus);
  const [note, setNote] = useState(plan.adminNote ?? "");
  const [isShared, setIsShared] = useState(plan.isShared);
  const sharingLocked = status === "archived";
  return <article className="rounded-2xl border border-[#e8dfd6] bg-[#fdfaf6] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-serif text-xl font-semibold">{plan.title}</p><p className="mt-1 text-xs text-[#786a5f]">{plan.ownerName ?? "이름 미설정"} · {plan.region} · {plan.scheduledFor ? new Date(plan.scheduledFor).toLocaleDateString("ko-KR") : "날짜 미정"}</p></div><select aria-label={`${plan.title} 운영 상태`} value={status} onChange={event => setStatus(event.target.value as ManagedPlan["adminStatus"])} className="h-9 rounded-lg border border-[#dfd2c5] bg-white px-3 text-xs font-bold text-[#725d4d]"><option value="active">정상</option><option value="review">검토 필요</option><option value="archived">아카이브</option></select></div><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-[#695c51]"><label className="inline-flex items-center gap-2 rounded-lg border border-[#dfd4c8] bg-white px-3 py-2 font-bold text-[#66584d]"><input aria-label={`${plan.title} 공유 허용`} type="checkbox" checked={isShared} disabled={sharingLocked} onChange={event => setIsShared(event.target.checked)} className="h-3.5 w-3.5 accent-[#52785e] disabled:cursor-not-allowed" />공유 링크 {isShared && !sharingLocked ? "허용" : "중지"}</label><span>예산 {plan.budgetLimit ? `${plan.budgetLimit.toLocaleString("ko-KR")}원` : "미정"}</span></div><textarea aria-label={`${plan.title} 운영 메모`} value={note} onChange={event => setNote(event.target.value)} placeholder="내부 운영 메모 (사용자에게 공개되지 않습니다)" className="mt-3 min-h-20 w-full rounded-lg border border-[#e3d9cf] bg-white p-3 text-xs leading-5 outline-none focus:border-[#a65e3b]" /><div className="mt-3 flex justify-end"><Button size="sm" disabled={saving} onClick={() => onSave({ planId: plan.id, adminStatus: status, adminNote: note || null, isShared: sharingLocked ? false : isShared })} className="rounded-lg bg-[#2d453a] text-xs text-white hover:bg-[#22372e]">운영 상태 저장</Button></div></article>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-[1.35rem] border border-[#e5dbd0] bg-white p-5"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#edf3ec] text-[#4d6e56]">{icon}</span><p className="mt-3 text-xs font-bold text-[#837468]">{label}</p><p className="mt-1 font-serif text-3xl font-semibold">{value}</p></div>; }
