import { ArrowLeft, ArrowUpRight, BookmarkCheck, Clock3, MapPinned, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { getPlace } from "@shared/travelCatalog";
import { getTravelGuide, travelGuides } from "@shared/travelGuides";
import BrandSeal from "@/components/BrandSeal";

export default function Guides() {
  return <div className="min-h-screen bg-[#f7f3ed] pb-20 text-[#302720]"><GuideHeader /><main className="mx-auto max-w-6xl px-5 py-10 lg:px-8 lg:py-16"><p className="text-xs font-bold tracking-[0.18em] text-[#a65d3a]">CURATED GUIDEBOOK</p><h1 className="mt-3 max-w-2xl font-serif text-4xl font-semibold tracking-tight sm:text-5xl">좋은 온기 여행은<br />준비하는 순간부터 시작됩니다.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#6c6056]">처음 가는 온천부터 1박 휴양까지, 과하지 않게 머물고 안전하게 돌아오기 위한 출처 기반 여행 가이드입니다.</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{travelGuides.map((guide, index) => <Link key={guide.slug} href={`/guides/${guide.slug}`} className="group rounded-[1.7rem] border border-[#e5d9cd] bg-white p-6 shadow-[0_14px_36px_-29px_rgba(58,38,20,.45)] transition hover:-translate-y-1 hover:shadow-[0_24px_42px_-28px_rgba(58,38,20,.36)]"><p className="text-xs font-bold tracking-[0.15em] text-[#a7603e]">{guide.eyebrow}</p><span className="mt-7 grid h-10 w-10 place-items-center rounded-full bg-[#e8efe7] font-serif text-lg text-[#385a46]">0{index + 1}</span><h2 className="mt-5 font-serif text-2xl font-semibold leading-8">{guide.title}</h2><p className="mt-3 min-h-24 text-sm leading-6 text-[#706359]">{guide.intro}</p><div className="mt-6 flex items-center justify-between border-t border-[#eee5db] pt-4 text-xs text-[#7a6b5d]"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" /> {guide.readMinutes}분 읽기</span><span className="inline-flex items-center gap-1 font-bold text-[#9e542f]">가이드 보기 <ArrowUpRight className="h-4 w-4" /></span></div></Link>)}</div></main></div>;
}

export function GuideDetail() {
  const [, params] = useRoute("/guides/:slug");
  const guide = getTravelGuide(params?.slug ?? "");
  if (!guide) return <div className="grid min-h-screen place-items-center bg-[#f7f3ed] text-center"><div><p className="font-serif text-3xl">가이드를 찾지 못했어요.</p><Link href="/guides" className="mt-4 inline-block text-sm font-bold text-[#a55231]">가이드 목록으로 돌아가기</Link></div></div>;
  return <div className="min-h-screen bg-[#f7f3ed] pb-20 text-[#302720]"><GuideHeader /><main className="mx-auto max-w-4xl px-5 py-10 lg:py-16"><Link href="/guides" className="inline-flex items-center gap-2 text-sm font-bold text-[#726357] hover:text-[#a55231]"><ArrowLeft className="h-4 w-4" /> 모든 가이드</Link><p className="mt-10 text-xs font-bold tracking-[0.18em] text-[#a65d3a]">{guide.eyebrow}</p><h1 className="mt-3 max-w-3xl font-serif text-4xl font-semibold tracking-tight sm:text-5xl">{guide.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#6c6056]">{guide.intro}</p><div className="mt-10 rounded-[1.6rem] border border-[#d8e4d7] bg-[#eff5ed] p-6"><div className="flex items-center gap-2 text-[#496e55]"><ShieldCheck className="h-4 w-4" /><p className="text-xs font-bold tracking-widest">TRAVEL ESSENTIALS</p></div><ul className="mt-4 grid gap-3 text-sm leading-6 text-[#536557] sm:grid-cols-2">{guide.essentials.map(item => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#73927a]" />{item}</li>)}</ul></div><div className="mt-10 space-y-8">{guide.sections.map((section, index) => <section key={section.title} className="grid gap-4 border-b border-[#e6ddd2] pb-8 sm:grid-cols-[52px_1fr]"><span className="font-serif text-3xl text-[#b66945]">0{index + 1}</span><div><h2 className="font-serif text-2xl font-semibold">{section.title}</h2><p className="mt-3 text-sm leading-7 text-[#675b51]">{section.body}</p></div></section>)}</div><section className="mt-10"><div className="flex items-center gap-2 text-[#a45734]"><MapPinned className="h-4 w-4" /><p className="text-xs font-bold tracking-widest">PLACES IN THIS GUIDE</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{guide.placeIds.map(id => { const place = getPlace(id); return place ? <Link key={id} href={`/places/${id}`} className="rounded-2xl border border-[#e5dbd0] bg-white p-5 transition hover:border-[#c77b57]"><p className="text-xs font-bold text-[#a65b37]">{place.region} · {place.city}</p><h3 className="mt-2 font-serif text-xl font-semibold">{place.name}</h3><p className="mt-2 text-sm leading-6 text-[#716257]">{place.summary}</p><p className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#4c7458]"><BookmarkCheck className="h-3.5 w-3.5" /> {place.verification.status === "official" ? "공식 정보 확인" : "큐레이션 초안"}</p></Link> : null; })}</div></section></main></div>;
}

function GuideHeader() { return <header className="border-b border-[#e7ddd2] bg-[#f7f3ed]/90 backdrop-blur"><div className="mx-auto flex h-[68px] max-w-6xl items-center justify-between px-5"><Link href="/" aria-label="온기행 홈"><BrandSeal compact /></Link><Link href="/" className="text-sm font-bold text-[#725f50] hover:text-[#a55231]">탐색으로 돌아가기</Link></div></header>; }
