import TravelMap from "@/components/TravelMap";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Bookmark, Check, Clock3, Heart, MapPinned, ShieldCheck, Sparkles, UtensilsCrossed } from "lucide-react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";

const categoryLabel = { sauna: "사우나", jjimjilbang: "찜질방", "hot-spring": "온천" } as const;

export default function PlaceDetail() {
  const [, params] = useRoute("/places/:id");
  const { isAuthenticated } = useAuth();
  const { data: place, isLoading, isError } = trpc.travel.catalog.byId.useQuery({ id: params?.id ?? "" });
  const { data: favoriteIds = [] } = trpc.travel.favorites.list.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const favorite = trpc.travel.favorites.toggle.useMutation({ onSuccess: data => { utils.travel.favorites.list.invalidate(); toast.success(data.saved ? "저장 목록에 담았어요." : "저장 목록에서 뺐어요."); } });
  const plan = trpc.travel.planner.create.useMutation({ onSuccess: () => toast.success("나의 여행 플랜에 새 하루를 만들었어요.") });
  const visit = trpc.travel.profile.addVisit.useMutation({ onSuccess: () => toast.success("방문 기록에 남겼어요.") });

  if (isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f3ed] text-sm text-[#706156]">장소의 온도를 불러오는 중입니다.</div>;
  if (!place) return <div className="grid min-h-screen place-items-center bg-[#f7f3ed]"><div role={isError ? "alert" : undefined} className="text-center"><p className="font-serif text-3xl">{isError ? "장소 정보를 불러오지 못했어요." : "장소를 찾지 못했어요."}</p><p className="mt-3 text-sm text-[#75685d]">잠시 후 다시 시도하거나, 탐색에서 다른 장소를 골라 보세요.</p><Link href="/" className="mt-4 inline-block text-sm font-bold text-[#a55231]">탐색으로 돌아가기</Link></div></div>;
  const saved = favoriteIds.includes(place.id);
  const handleSave = () => { if (!isAuthenticated) return startLogin(); favorite.mutate({ placeId: place.id }); };
  const handlePlan = () => { if (!isAuthenticated) return startLogin(); plan.mutate({ title: `${place.region}에서 보내는 느린 하루`, region: place.region, coverPlaceId: place.id }); };
  const handleVisit = () => { if (!isAuthenticated) return startLogin(); visit.mutate({ placeId: place.id }); };

  return <div className="min-h-screen bg-[#f7f3ed] pb-20 text-[#322820] md:pb-0"><header className="border-b border-[#e9dfd4] bg-[#f7f3ed]/90 backdrop-blur"><div className="mx-auto flex h-[68px] max-w-5xl items-center justify-between px-5"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#63564c]"><ArrowLeft className="h-4 w-4" /> 탐색으로</Link><Link href="/" className="font-serif text-xl font-semibold">온기행</Link><button onClick={handleSave} className={`grid h-9 w-9 place-items-center rounded-full ${saved ? "bg-[#b8653a] text-white" : "bg-white text-[#7a6757]"}`}><Heart className={`h-4 w-4 ${saved ? "fill-current" : ""}`} /></button></div></header>
    <main className="mx-auto max-w-5xl px-5 pb-14 pt-8 lg:pt-12"><div className="grid gap-9 lg:grid-cols-[1.08fr_0.92fr]"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#f0e3d4] px-3 py-1 text-xs font-bold text-[#985234]">{categoryLabel[place.category]}</span><span className="rounded-full bg-[#ebf0eb] px-3 py-1 text-xs font-bold text-[#45604e]">{place.region} · {place.city}</span></div><h1 className="mt-5 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">{place.name}</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#66594e]">{place.summary}</p><div className="mt-7 rounded-[1.4rem] bg-[#2d453a] p-5 text-[#faf7f0]"><p className="text-xs font-bold tracking-widest text-[#e9b28e]">THE HIGHLIGHT</p><p className="mt-2 font-serif text-xl leading-7">{place.highlight}</p><div className="mt-5 flex items-center gap-2 text-sm text-[#e5eadf]"><Clock3 className="h-4 w-4 text-[#e9b28e]" /> 여유 있게 {Math.round(place.durationMinutes / 60)}시간 안팎을 권합니다.</div></div></div><div className="overflow-hidden rounded-[1.65rem] border border-[#e3d9cd] bg-white p-2 shadow-[0_18px_42px_-31px_rgba(58,38,20,.45)]"><TravelMap places={[place]} className="h-[310px] overflow-hidden rounded-[1.25rem]" /></div></div>
      <div className="mt-10 grid gap-5 lg:grid-cols-[1.08fr_0.92fr]"><section className="rounded-[1.6rem] border border-[#e4dad0] bg-[#fffcf8] p-6"><div className="flex items-center gap-2 text-[#a35431]"><Sparkles className="h-4 w-4" /><p className="text-xs font-bold tracking-widest">GOOD TO KNOW</p></div><h2 className="mt-3 font-serif text-2xl font-semibold">이렇게 머물러 보세요.</h2><p className="mt-3 text-sm leading-6 text-[#6c5f54]">{place.usageTip}</p><div className="mt-5 flex flex-wrap gap-2">{[...place.mood, ...place.facilities].map(tag => <span key={tag} className="rounded-full bg-[#f3ede5] px-3 py-1.5 text-xs text-[#665a51]">{tag}</span>)}</div><div className="mt-7 flex flex-wrap gap-3"><Button onClick={handlePlan} disabled={plan.isPending} className="h-11 rounded-full bg-[#b8653a] px-5 text-sm font-bold text-white hover:bg-[#a55330]"><Bookmark className="mr-2 h-4 w-4" /> 플랜에 담기</Button><Button onClick={handleVisit} disabled={visit.isPending} variant="outline" className="h-11 rounded-full border-[#d8caba] bg-white px-5 text-sm font-bold text-[#6b5647]"><Check className="mr-2 h-4 w-4" /> 다녀왔어요</Button></div></section>
        <section className="rounded-[1.6rem] bg-[#e9efe9] p-6"><div className="flex items-center gap-2 text-[#496552]"><ShieldCheck className="h-4 w-4" /><p className="text-xs font-bold tracking-widest">SAUNA SCIENCE HUB</p></div><h2 className="mt-3 font-serif text-2xl font-semibold">{place.science.title}</h2><p className="mt-3 text-sm leading-6 text-[#53645a]">{place.science.summary}</p><p className="mt-4 text-xs font-semibold text-[#4d6555]">{place.science.studyType}</p><a href={place.science.sourceUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#3e634d] hover:underline">연구 탐색으로 이동 <ArrowLeft className="h-4 w-4 rotate-180" /></a><p className="mt-4 border-t border-[#cdd8cd] pt-3 text-[11px] leading-5 text-[#66766c]">일반적인 연구 정보이며 의료 조언이나 효능 보장이 아닙니다.</p></section></div>
      <section className="mt-5 rounded-[1.6rem] border border-[#e4dad0] bg-white p-6"><div className="flex items-center gap-2 text-[#a35431]"><MapPinned className="h-4 w-4" /><p className="text-xs font-bold tracking-widest">AROUND THE WARMTH</p></div><h2 className="mt-3 font-serif text-2xl font-semibold">근처에서 이어지는 좋은 장면</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{place.neighborhood.map(item => <div key={item.title} className="rounded-2xl bg-[#faf6f0] p-4"><div className="flex items-center gap-2 text-[#a15a39]">{item.type === "food" ? <UtensilsCrossed className="h-4 w-4" /> : <MapPinned className="h-4 w-4" />}<span className="text-xs font-bold">{item.type === "food" ? "맛있는 연결" : "잠깐의 산책"}</span></div><h3 className="mt-3 font-serif text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[#72665b]">{item.description}</p></div>)}</div></section>
    </main></div>;
}
