// tourAPI 동기화 스크립트 (하이브리드 전략)
// 사우나/온천 = curated seed 유지, 맛집/볼거리 = tourAPI 보강
// 실행: TOURAPI_KEY=xxx node scripts/sync-tourapi.mjs
// 결과: src/data/seed.enriched.ts 생성
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/data/seed.enriched.ts");
const KEY = process.env.TOURAPI_KEY;
if (!KEY) { console.error("TOURAPI_KEY env 필요"); process.exit(1); }

const REGIONS = [
  { id: "seoul", areaCode: "1" }, { id: "incheon", areaCode: "2" },
  { id: "daejeon", areaCode: "3" }, { id: "daegu", areaCode: "4" },
  { id: "gwangju", areaCode: "5" }, { id: "busan", areaCode: "6" },
  { id: "gangwon", areaCode: "32" }, { id: "gyeongju", areaCode: "35" },
  { id: "jeju", areaCode: "39" },
];

async function fetchAll(areaCode, contentTypeId) {
  const out = [];
  for (let page = 1; page <= 5; page++) {
    const qs = new URLSearchParams({
      serviceKey: KEY, MobileOS: "ETC", MobileApp: "saunaplanner", _type: "json",
      numOfRows: "100", pageNo: String(page), areaCode, contentTypeId,
    });
    const res = await fetch(`https://apis.data.go.kr/B551011/KorService2/areaBasedList2?${qs}`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const json = await res.json();
    const raw = json?.response?.body?.items?.item;
    if (!raw) break;
    const arr = Array.isArray(raw) ? raw : [raw];
    for (const it of arr) if (it.title) out.push(it);
    if (arr.length < 100) break;
  }
  return out;
}

// 사우나 키워드 — 볼거리에서 사우나계 제외용(불용어 없음, 엄격)
const SAUNA_KW = ["온천", "사우나", "찜질", "스파", "목욕", "욕장", "찜질방"];

async function collect() {
  const stats = [];
  for (const r of REGIONS) {
    let food = [], attr = [];
    try { food = await fetchAll(r.areaCode, "39"); } catch (e) { console.warn(`${r.id} food 실패`, e.message); }
    try { attr = await fetchAll(r.areaCode, "12"); } catch (e) { console.warn(`${r.id} attr 실패`, e.message); }
    const foodTitles = food.slice(0, 5).map((i) => i.title);
    const attrTitles = attr
      .filter((i) => !SAUNA_KW.some((k) => (i.title || "").includes(k)))
      .slice(0, 5).map((i) => i.title);
    stats.push({ region: r.id, foodCount: food.length, attrCount: attr.length, foodTitles, attrTitles });
  }
  return stats;
}

const data = await collect();
const ts = `// auto-generated by scripts/sync-tourapi.mjs — ${new Date().toISOString()}
// 하이브리드: 사우나/온천=curated, 맛집/볼거리=tourAPI 보강.
// CI에서 생성 권장(커밋 제외).
export const enrichedSummary = ${JSON.stringify(data, null, 2)};
`;
writeFileSync(OUT, ts);
console.log("생성 완료:", OUT);
console.log(JSON.stringify(data, null, 2));
