import { Button } from "@/components/ui/button";
import { Check, Clock3, Copy, ListChecks, Save, Send, Trash2, Wallet } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type PlanStop = { id: number; placeId: string; position: number; note: string | null; startTime: string | null; estimatedCost: number | null; durationMinutes: number | null };
type ChecklistItem = { id: number; label: string; isCompleted: boolean };
type Plan = { id: number; title: string; region: string; scheduledFor: Date | null; budgetLimit: number | null; isShared: boolean; shareToken: string | null; stops: PlanStop[]; checklist: ChecklistItem[] };
type CatalogPlace = { id: string; name: string; region: string };

type Props = {
  plan: Plan;
  catalog: CatalogPlace[];
  onAddStop: (placeId: string) => void;
  onRemoveStop: (stopId: number) => void;
  onMove: (stopId: number, direction: "up" | "down") => void;
  onUpdateStop: (stopId: number, input: Partial<Omit<PlanStop, "id" | "placeId" | "position">>) => void;
  onUpdatePlan: (input: { title: string; scheduledFor: Date | null; budgetLimit: number | null }) => void;
  onAddChecklist: (label: string) => void;
  onToggleChecklist: (itemId: number, isCompleted: boolean) => void;
  onRemoveChecklist: (itemId: number) => void;
  onShare: (isShared: boolean) => Promise<{ shareToken: string | null }>;
};

export default function TripPlanStudio({ plan, catalog, onAddStop, onRemoveStop, onMove, onUpdateStop, onUpdatePlan, onAddChecklist, onToggleChecklist, onRemoveChecklist, onShare }: Props) {
  const [title, setTitle] = useState(plan.title);
  const [scheduledFor, setScheduledFor] = useState(plan.scheduledFor ? formatDateInput(plan.scheduledFor) : "");
  const [budget, setBudget] = useState(plan.budgetLimit?.toString() ?? "");
  const [checklistLabel, setChecklistLabel] = useState("");
  const totalCost = useMemo(() => plan.stops.reduce((sum, stop) => sum + (stop.estimatedCost ?? 0), 0), [plan.stops]);
  const completed = plan.checklist.filter(item => item.isCompleted).length;
  const choices = catalog.filter(place => place.region === plan.region && !plan.stops.some(stop => stop.placeId === place.id));
  const savePlan = () => onUpdatePlan({ title: title.trim() || plan.title, scheduledFor: scheduledFor ? new Date(`${scheduledFor}T00:00:00.000Z`) : null, budgetLimit: budget ? Number(budget) : null });
  const shareUrl = plan.shareToken ? `${window.location.origin}/share/${plan.shareToken}` : null;

  return <div id="trip-plans" className="scroll-mt-6 rounded-[1.5rem] border border-[#ded6ca] bg-[#fffdfa] p-5 shadow-[0_12px_30px_-26px_rgba(58,38,20,.42)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-widest text-[#a45d3a]">ITINERARY STUDIO</p><input aria-label="플랜 이름" value={title} onChange={event => setTitle(event.target.value)} className="mt-2 w-full border-0 bg-transparent font-serif text-2xl font-semibold outline-none focus:ring-0" /></div><span className="rounded-full bg-[#eff5ed] px-3 py-1.5 text-xs font-bold text-[#446d51]">{plan.stops.length}곳 · {plan.region}</span></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="rounded-xl border border-[#e9dfd4] bg-[#fbf8f3] p-3"><span className="text-[10px] font-bold tracking-widest text-[#89786a]">여행 날짜</span><input aria-label="여행 날짜" type="date" value={scheduledFor} onChange={event => setScheduledFor(event.target.value)} className="mt-1 block w-full border-0 bg-transparent p-0 text-sm font-semibold outline-none" /></label><label className="rounded-xl border border-[#e9dfd4] bg-[#fbf8f3] p-3"><span className="text-[10px] font-bold tracking-widest text-[#89786a]">예산 상한 (원)</span><input aria-label="예산 상한" type="number" min="0" value={budget} onChange={event => setBudget(event.target.value)} placeholder="예: 80000" className="mt-1 block w-full border-0 bg-transparent p-0 text-sm font-semibold outline-none" /></label></div>
    <div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-[#706257]">{scheduledFor ? `${scheduledFor.replaceAll("-", ".")} 여행` : "날짜 미정"} · 장소 예상 비용 {totalCost.toLocaleString("ko-KR")}원</p><Button size="sm" onClick={savePlan} className="rounded-lg bg-[#2d453a] text-xs text-white hover:bg-[#22372e]"><Save className="mr-1 h-3.5 w-3.5" /> 기본 정보 저장</Button></div>
    {plan.budgetLimit !== null && <div className="mt-4 rounded-xl bg-[#f1ece3] px-4 py-3 text-xs text-[#685c50]"><span className="inline-flex items-center gap-1 font-bold text-[#8f512f]"><Wallet className="h-3.5 w-3.5" /> 예산 현황</span><span className="ml-2">예상 {totalCost.toLocaleString("ko-KR")}원 / 상한 {plan.budgetLimit.toLocaleString("ko-KR")}원</span>{totalCost > plan.budgetLimit && <span className="ml-2 font-bold text-[#aa4f35]">상한을 넘었어요.</span>}</div>}
    <div className="mt-6"><div className="flex items-center justify-between"><p className="text-xs font-bold tracking-widest text-[#9a6043]">DAY FLOW</p><span className="text-xs text-[#796b60]">시간·예상 비용·메모를 저장하세요.</span></div><div className="mt-3 space-y-3">{plan.stops.map((stop, index) => <StopEditor key={stop.id} stop={stop} place={catalog.find(place => place.id === stop.placeId)} index={index} total={plan.stops.length} onMove={onMove} onRemove={onRemoveStop} onSave={input => onUpdateStop(stop.id, input)} />)}</div>{choices.length > 0 && <select aria-label={`${plan.title}에 장소 추가`} defaultValue="" onChange={event => { if (event.target.value) { onAddStop(event.target.value); event.currentTarget.value = ""; } }} className="mt-3 h-10 w-full rounded-xl border border-dashed border-[#d8c9b8] bg-white px-3 text-xs font-semibold text-[#846856] outline-none"><option value="">+ 이 플랜에 장소 추가</option>{choices.map(place => <option key={place.id} value={place.id}>{place.name}</option>)}</select>}</div>
    <div className="mt-6 rounded-2xl bg-[#eef4ed] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[#476c53]"><ListChecks className="h-4 w-4" /><p className="text-xs font-bold tracking-widest">PREP CHECKLIST</p></div><span className="text-xs font-bold text-[#597560]">{completed}/{plan.checklist.length}</span></div><div className="mt-3 space-y-2">{plan.checklist.map(item => <div key={item.id} className="flex items-center gap-2"><button aria-label={`${item.label} 완료 상태 변경`} onClick={() => onToggleChecklist(item.id, !item.isCompleted)} className={`grid h-5 w-5 place-items-center rounded border ${item.isCompleted ? "border-[#52785e] bg-[#52785e] text-white" : "border-[#9cb4a0] bg-white"}`}>{item.isCompleted && <Check className="h-3.5 w-3.5" />}</button><span className={`flex-1 text-sm ${item.isCompleted ? "text-[#718572] line-through" : "text-[#4d6250]"}`}>{item.label}</span><button aria-label={`${item.label} 삭제`} onClick={() => onRemoveChecklist(item.id)} className="text-[#a86145]"><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div><form className="mt-3 flex gap-2" onSubmit={event => { event.preventDefault(); if (checklistLabel.trim()) { onAddChecklist(checklistLabel.trim()); setChecklistLabel(""); } }}><input aria-label="준비물 추가" value={checklistLabel} onChange={event => setChecklistLabel(event.target.value)} placeholder="예: 수분 보충용 물" className="h-9 min-w-0 flex-1 rounded-lg border border-[#cfddcf] bg-white px-3 text-xs outline-none" /><Button type="submit" size="sm" className="h-9 rounded-lg bg-[#53775e] text-xs text-white hover:bg-[#41634b]">추가</Button></form></div>
    <div className="mt-5 border-t border-[#eee4d9] pt-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold tracking-widest text-[#a26040]">SHARE PLAN</p><p className="mt-1 text-xs text-[#75675c]">공유를 켜면 링크를 아는 사람에게 읽기 전용 일정이 보입니다.</p></div><Button variant="outline" onClick={async () => { const result = await onShare(!plan.isShared); toast.success(result.shareToken ? "공유 링크를 준비했어요." : "공유를 중지했어요."); }} className="rounded-lg border-[#d8c5b4] text-xs text-[#8f4f2f]"><Send className="mr-1 h-3.5 w-3.5" /> {plan.isShared ? "공유 중지" : "공유 켜기"}</Button></div>{plan.isShared && shareUrl && <div className="mt-3 flex gap-2"><input aria-label="공유 링크" value={shareUrl} readOnly className="h-9 min-w-0 flex-1 rounded-lg border border-[#e3d8ce] bg-[#fbf8f3] px-3 text-[11px] text-[#72655a]" /><Button size="sm" onClick={async () => { await navigator.clipboard.writeText(shareUrl); toast.success("공유 링크를 복사했어요."); }} className="h-9 rounded-lg bg-[#a75d39] text-xs text-white hover:bg-[#914a2c]"><Copy className="mr-1 h-3.5 w-3.5" /> 복사</Button></div>}</div>
  </div>;
}

function StopEditor({ stop, place, index, total, onMove, onRemove, onSave }: { stop: PlanStop; place?: CatalogPlace; index: number; total: number; onMove: (id: number, direction: "up" | "down") => void; onRemove: (id: number) => void; onSave: (input: Partial<Omit<PlanStop, "id" | "placeId" | "position">>) => void }) {
  const [time, setTime] = useState(stop.startTime ?? "");
  const [cost, setCost] = useState(stop.estimatedCost?.toString() ?? "");
  const [duration, setDuration] = useState(stop.durationMinutes?.toString() ?? "");
  const [note, setNote] = useState(stop.note ?? "");
  const changed = time !== (stop.startTime ?? "") || cost !== (stop.estimatedCost?.toString() ?? "") || duration !== (stop.durationMinutes?.toString() ?? "") || note !== (stop.note ?? "");
  return <div className="rounded-xl border border-[#e9dfd4] bg-white p-3"><div className="flex items-center gap-2"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#f0e2d5] text-[11px] font-bold text-[#a45b38]">{index + 1}</span><p className="min-w-0 flex-1 truncate text-sm font-bold">{place?.name ?? "장소"}</p><button aria-label="순서 위로" disabled={index === 0} onClick={() => onMove(stop.id, "up")} className="text-[#806957] disabled:opacity-25">↑</button><button aria-label="순서 아래로" disabled={index === total - 1} onClick={() => onMove(stop.id, "down")} className="text-[#806957] disabled:opacity-25">↓</button><button aria-label="장소 삭제" onClick={() => onRemove(stop.id)} className="text-[#a65b3c]"><Trash2 className="h-3.5 w-3.5" /></button></div><div className="mt-3 grid grid-cols-3 gap-2"><label className="text-[10px] font-bold text-[#867669]">시작<input aria-label={`${place?.name ?? "장소"} 시작 시간`} type="time" value={time} onChange={event => setTime(event.target.value)} className="mt-1 block h-8 w-full rounded-lg border border-[#eadfd4] px-2 text-xs font-medium outline-none" /></label><label className="text-[10px] font-bold text-[#867669]">비용<input aria-label={`${place?.name ?? "장소"} 예상 비용`} type="number" min="0" value={cost} onChange={event => setCost(event.target.value)} className="mt-1 block h-8 w-full rounded-lg border border-[#eadfd4] px-2 text-xs font-medium outline-none" /></label><label className="text-[10px] font-bold text-[#867669]">체류(분)<input aria-label={`${place?.name ?? "장소"} 체류 시간`} type="number" min="0" max="1440" value={duration} onChange={event => setDuration(event.target.value)} className="mt-1 block h-8 w-full rounded-lg border border-[#eadfd4] px-2 text-xs font-medium outline-none" /></label></div><div className="mt-2 flex gap-2"><input aria-label={`${place?.name ?? "장소"} 메모`} value={note} onChange={event => setNote(event.target.value)} placeholder="이 장소에서의 메모" className="h-8 min-w-0 flex-1 border-0 text-xs outline-none placeholder:text-[#a99d91]" /><Button size="sm" disabled={!changed} onClick={() => onSave({ startTime: time || null, estimatedCost: cost ? Number(cost) : null, durationMinutes: duration ? Number(duration) : null, note: note || null })} className="h-8 rounded-lg bg-[#f0e3d5] px-2 text-[10px] font-bold text-[#9a5232] hover:bg-[#ead8c8] disabled:opacity-40"><Save className="mr-1 h-3 w-3" /> 저장</Button></div></div>;
}

function formatDateInput(value: Date) { return new Date(value).toISOString().slice(0, 10); }
