// auto-generated by scripts/sync-tourapi.mjs — 2026-07-09T08:48:05.097Z
// 하이브리드: 사우나/온천=curated(seed.ts), 맛집/볼거리/숙소=tourAPI 실데이터 보강(이 파일).
// seed.ts가 이 파일을 optional import하여 지역별 places에 병합합니다.
import type { Place } from "./schema";

// 지역별 tourAPI 보강 장소 (맛집/볼거리/숙소 - 실좌표 포함)
export const enrichedPlaces: Record<string, Place[]> = {
  "seoul": [],
  "incheon": [],
  "daejeon": [],
  "daegu": [],
  "gwangju": [],
  "busan": [],
  "gangwon": [],
  "gyeongju": [],
  "jeju": []
};

// 수집 요약 (모니터링/디버그용)
export const enrichedSummary = [
  {
    "region": "seoul",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "incheon",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "daejeon",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "daegu",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "gwangju",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "busan",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "gangwon",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "gyeongju",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  },
  {
    "region": "jeju",
    "foodCount": 0,
    "attrCount": 0,
    "stayCount": 0,
    "stayWithOnsen": 0,
    "stayTitles": []
  }
];
