// auto-generated by scripts/sync-tourapi.mjs — 2026-07-09T07:24:38.136Z
// 하이브리드: 사우나/온천=curated(seed.ts), 맛집/볼거리=tourAPI 보강(이 파일).
// seed.ts가 이 파일을 optional import하여 지역별 places에 병합합니다.
import type { Place } from "./schema";

// 지역별 tourAPI 보강 장소 (맛집/볼거리)
export const enrichedPlaces: Record<string, Place[]> = {
  "seoul": [
    {
      "id": "seoul-food-api-1",
      "name": "가나돈까스의집",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 강남구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강남구 언주로 608",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-2",
      "name": "가담",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 강남구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강남구 언주로167길 35 (신사동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-3",
      "name": "가막골흑염소요리전문점",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 강서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강서구 화곡로56길 37-11",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-4",
      "name": "가문",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 강북구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강북구 노해로 13",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-5",
      "name": "가산물갈비&백년불고기",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 금천구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 금천구 가산디지털1로 128 에스티엑스브이타워",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-6",
      "name": "가야밀냉면해물칼국수",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 은평구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 은평구 대서문길 36 (진관동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-7",
      "name": "가양칼국수버섯매운탕",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 영등포구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 영등포구 국제금융로 78 (여의도동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-food-api-8",
      "name": "가조쿠",
      "type": "restaurant",
      "region": "seoul",
      "city": "서울특별시 성동구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 성동구 연무장길 31-2 (성수동2가)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-1",
      "name": "가회동성당",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 종로구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 종로구 북촌로 57 (가회동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-2",
      "name": "갈산공원",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 양천구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 양천구 신정동 162-56",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-3",
      "name": "강남",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 강남구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강남구 압구정로 161 (압구정동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-4",
      "name": "강남 마이스 관광특구",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 강남구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강남구 영동대로 513 (삼성동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-5",
      "name": "강서습지생태공원",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 강서구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강서구 양천로27길 279-23",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-6",
      "name": "강서역사문화거리",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 강서구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 강서구 양천로 291 (마곡동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-7",
      "name": "개봉유수지 생태공원",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 구로구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 구로구 개봉동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "seoul-att-api-8",
      "name": "거리공원",
      "type": "attraction",
      "region": "seoul",
      "city": "서울특별시 구로구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "서울특별시 구로구 구로동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "incheon": [
    {
      "id": "incheon-food-api-1",
      "name": "가마솥손두부",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 미추홀구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 미추홀구 소성로326번길 4 (문학동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-2",
      "name": "가연식당",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 제물포구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 제물포구 어촌로 7 (만석동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-3",
      "name": "가온칼국수 송도본점",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 연수구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 연수구 송도과학로28번길 8 (송도동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-4",
      "name": "가현산 잔치국수",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 검단구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 검단구 대곡로368번길 25 (대곡동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-5",
      "name": "가회동샤브칼국수 송도컨벤시아점",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 연수구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 연수구 센트럴로 123 (송도동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-6",
      "name": "강화국수",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 동문안길 12-1 삼성양복점",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-7",
      "name": "강화섬약쑥한우",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 선원면 선원사지로 32",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-food-api-8",
      "name": "강화손칼국수 본점",
      "type": "restaurant",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 양도면 강화남로 678",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-1",
      "name": "감중공원",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 서해구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 서해구 가정로98번길 18",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-2",
      "name": "갑곶돈대",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 강화읍 해안동로1366번길 18",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-3",
      "name": "갑곶순교성지",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 강화읍 해안동로1366번길 35",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-4",
      "name": "강화 사기리 탱자나무",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 화도면 해안남로1114번길 6",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-5",
      "name": "강화 삼랑성",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 길상면 온수리",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-6",
      "name": "강화 서도 중앙교회",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 서도면 주문도길 256-1",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-7",
      "name": "강화 아르미애월드",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 불은면 중앙로 742-2",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "incheon-att-api-8",
      "name": "강화 오상리 고인돌군",
      "type": "attraction",
      "region": "incheon",
      "city": "인천광역시 강화군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "인천광역시 강화군 내가면 오상리",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "daejeon": [
    {
      "id": "daejeon-food-api-1",
      "name": "가나샤브샤브",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 신성로84번길 49",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-2",
      "name": "가남지",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 대덕대로 588",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-3",
      "name": "가데나 레스토랑",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 반석로 136-6 (반석동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-4",
      "name": "간사이",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 온천서로 8-13 (봉명동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-5",
      "name": "갈마짬뽕",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 서구 월평동로 5-11 (갈마동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-6",
      "name": "갈밭식당",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 대덕구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 대덕구 대청호수로 1553",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-7",
      "name": "갑동숯골냉면",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 현충원로 173",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-food-api-8",
      "name": "개천식당",
      "type": "restaurant",
      "region": "daejeon",
      "city": "대전광역시 동구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 동구 대전로779번길 41-1 (원동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-1",
      "name": "갑천",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 구성동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-2",
      "name": "광수사",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 학하서로63번길 26 (계산동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-3",
      "name": "국립대전숲체원",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 숲체원로 124 (성북동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-4",
      "name": "국립대전현충원 보훈둘레길",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 유성구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 유성구 현충원로 251",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-5",
      "name": "금강로하스 대청공원 (암석식물원)",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 대덕구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 대덕구 미호동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-6",
      "name": "금강로하스대청공원",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 대덕구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 대덕구 미호동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-7",
      "name": "금강로하스산호빛공원",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 대덕구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 대덕구 석봉동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daejeon-att-api-8",
      "name": "길치문화공원",
      "type": "attraction",
      "region": "daejeon",
      "city": "대전광역시 대덕구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대전광역시 대덕구 신상로 65-100 (비래동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "daegu": [
    {
      "id": "daegu-food-api-1",
      "name": "가야성",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 달서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달서구 월배로83길 7 (송현동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-2",
      "name": "가원식당",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 동구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 동구 팔공산로199길 6-3 (용수동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-3",
      "name": "가창닭갈비",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 달성군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달성군 가창면 가창로119길 13",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-4",
      "name": "갈비만 대구본점",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 달서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달서구 조암로 58",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-5",
      "name": "감나무집",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 달성군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달성군 우록3길 73",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-6",
      "name": "거산 이가네더덕밥",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 북구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 북구 이곡길 35-41 (서변동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-7",
      "name": "걸리버막창",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 북구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 북구 옥산로 53 (노원동1가)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-food-api-8",
      "name": "게이블루프커피",
      "type": "restaurant",
      "region": "daegu",
      "city": "대구광역시 달성군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달성군 다사읍 강정본길 77",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-1",
      "name": "가창 찐빵 골목",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 달성군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달성군 가창면 가창로 1099",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-2",
      "name": "감삼못공원",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 서구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 서구 서대구로3길 43 (내당동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-3",
      "name": "강정고령보",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 달성군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 달성군 다사읍 강정본길 57",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-4",
      "name": "경극고택",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 동구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 동구 옻골로 195-3",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-5",
      "name": "경상감영공원",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 중구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 중구 경상감영길 99",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-6",
      "name": "고산골 메타쉐콰이어길",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 남구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 남구 용두2길 43",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-7",
      "name": "고산서당",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 수성구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 수성구 성동로37길 39-3",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "daegu-att-api-8",
      "name": "공룡공원",
      "type": "attraction",
      "region": "daegu",
      "city": "대구광역시 남구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "대구광역시 남구 용두2길 43",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "gwangju": [
    {
      "id": "gwangju-food-api-1",
      "name": "가배당",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 서구 눌재로 434",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-2",
      "name": "개마고원",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 서구 상무대로 1094",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-3",
      "name": "갤러리24",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 서구 천변좌로 14",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-4",
      "name": "계림동잔치집",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 동구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 동구 무등로306번길 6-1",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-5",
      "name": "광후장어",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 광산구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 광산구 임방울대로 503",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-6",
      "name": "금강한우전문식육식당",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 서구 천변우하로 373",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-7",
      "name": "금다연한정식",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 서구 상무연하로 72",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-food-api-8",
      "name": "금당",
      "type": "restaurant",
      "region": "gwangju",
      "city": "전남광주통합특별시 서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 서구 송풍로17번길 15 (풍암동, 수정빌라)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-1",
      "name": "경암근린공원",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 광산구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 광산구 하남대로54번안길 133 (하남동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-2",
      "name": "관덕정의 각궁",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 남구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 남구 사직길 49",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-3",
      "name": "광주 경찰충혼탑",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 남구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 남구 사직길 49",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-4",
      "name": "광주 송정동 떡갈비 골목",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 광산구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 광산구 광산로29번길",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-5",
      "name": "광주 수완호수공원",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 광산구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 광산구 장신로82번길 57 공원관리사무소",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-6",
      "name": "광주 충효동 왕버들 군",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 북구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 북구 충효샘길 7",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-7",
      "name": "광주 평촌마을",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 북구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 북구 평촌길 15",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gwangju-att-api-8",
      "name": "광주폴리",
      "type": "attraction",
      "region": "gwangju",
      "city": "전남광주통합특별시 북구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "전남광주통합특별시 북구 비엔날레로 111",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "busan": [
    {
      "id": "busan-food-api-1",
      "name": "가마솥생복집",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 기장군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 기장군 차성로 327-2 가마솥생복집",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-2",
      "name": "가야포차선지국",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 기장군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 기장군 정관읍 정관8로 28",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-3",
      "name": "가야할매 밀면",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 연제구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 연제구 월드컵대로145번길 32",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-4",
      "name": "감포참가자미",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 동구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 동구 범일로102번길 16-20 (범일동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-5",
      "name": "강호중마라도물회",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 강서구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 강서구 녹산화전로 283 (녹산동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-6",
      "name": "개금밀면",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 부산진구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 부산진구 가야대로482번길 9-4",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-7",
      "name": "개미집 본점",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 중구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 중구 중구로30번길 21-1 (신창동2가)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-food-api-8",
      "name": "거대갈비",
      "type": "restaurant",
      "region": "busan",
      "city": "부산광역시 해운대구",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 해운대구 달맞이길 22 (중동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-1",
      "name": "가덕도 등대",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 강서구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 강서구 외양포로 10",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-2",
      "name": "가덕도 연대봉",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 강서구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 강서구 천성동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-3",
      "name": "가톨릭 특성화 거리",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 금정구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 금정구 부곡동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-4",
      "name": "감지해변",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 영도구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 영도구 감지길 110",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-5",
      "name": "감천사(부산)",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 연제구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 연제구 묘봉산로 40",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-6",
      "name": "경상좌수영성지",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 수영구",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 수영구 수영성로 43",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-7",
      "name": "곰내연밭",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 기장군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 기장군 철마면 웅천리 254-4",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "busan-att-api-8",
      "name": "공수어촌체험마을",
      "type": "attraction",
      "region": "busan",
      "city": "부산광역시 기장군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "부산광역시 기장군 기장읍 공수해안길 13-2",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "gangwon": [
    {
      "id": "gangwon-food-api-1",
      "name": "가고파부치기",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 평창군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 평창군 평창읍 평창시장1길 14",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-2",
      "name": "가람집옹심이",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 강릉시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 강릉시 공항길30번길 16",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-3",
      "name": "가리왕산가든",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 평창군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 평창군 대화면 가평로 5",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-4",
      "name": "가방속커피향기",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 평창군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 평창군 봉평면 기풍3길 29",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-5",
      "name": "가보자순대국",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 춘천시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 춘천시 율문2길 11",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-6",
      "name": "가시머리식당",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 평창군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 평창군 대관령면 대관령마루길 369",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-7",
      "name": "갈매기다방",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 강릉시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 강릉시 연곡면 영진길 63",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-food-api-8",
      "name": "갈매기횟집",
      "type": "restaurant",
      "region": "gangwon",
      "city": "강원특별자치도 고성군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 고성군 아야진해변길 80 동해활어, 처갓집양념통닭",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-1",
      "name": "가람리조트",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 홍천군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 홍천군 두촌면 부채들길 29",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-2",
      "name": "가리왕산케이블카",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 정선군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 정선군 북평면 중봉길 41-35",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-3",
      "name": "가원습지 생태자연공원",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 동해시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 동해시 지가동 77-6",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-4",
      "name": "간이해변",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 속초시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 속초시 아바이마을1길 86-1 (청호동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-5",
      "name": "간현관광지",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 원주시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 원주시 소금산길 12",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-6",
      "name": "갈남항",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 삼척시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 삼척시 원덕읍 갈남리 99-20",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-7",
      "name": "갈천약수터",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 양양군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 양양군 서면 구룡령로 1103-66",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gangwon-att-api-8",
      "name": "감성공작소",
      "type": "attraction",
      "region": "gangwon",
      "city": "강원특별자치도 삼척시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "강원특별자치도 삼척시 대학로 13-1 (당저동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "gyeongju": [
    {
      "id": "gyeongju-food-api-1",
      "name": "가마솥 양푼이 밥상",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 경주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경주시 북군3길 12-1",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-2",
      "name": "가봉반과",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 경주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경주시 첨성로 61-7",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-3",
      "name": "가정초밥 효자점",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 포항시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 포항시 남구 효자동길2번길 3 효자역전종합상가",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-4",
      "name": "갈치조림 토박이식당",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 경주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경주시 북군길 21",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-5",
      "name": "개운궁",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 상주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 상주시 경상대로 2882 (개운동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-6",
      "name": "개울가식당",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 경산시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경산시 와촌면 갓바위로81길 7-5",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-7",
      "name": "개진고로케",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 고령군",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 고령군 대가야읍 장기터길 15-2",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-food-api-8",
      "name": "경산예찬한우",
      "type": "restaurant",
      "region": "gyeongju",
      "city": "경상북도 경산시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경산시 남매로 251",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-1",
      "name": "가래실문화마을(별별미술마을)",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 영천시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 영천시 화산면 가래실로 364",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-2",
      "name": "가산수피아",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 칠곡군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 칠곡군 가산면 학하들안2길 105",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-3",
      "name": "가오실공원",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 예천군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 예천군 개포면 가곡리",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-4",
      "name": "감못(부지)",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 경산시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경산시 감못둑길 20 (갑제동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-5",
      "name": "감응사(성주)",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 성주군",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 성주군 월항면 대산1길 234",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-6",
      "name": "감포항",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 경주시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경주시 감포읍 감포로",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-7",
      "name": "강동 워터파크",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 경주시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경주시 보불로 391 (천군동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "gyeongju-att-api-8",
      "name": "강동리조트 프라이빗콘도",
      "type": "attraction",
      "region": "gyeongju",
      "city": "경상북도 경주시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "경상북도 경주시 보불로 391 (천군동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ],
  "jeju": [
    {
      "id": "jeju-food-api-1",
      "name": "가는곶 세화",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 제주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 제주시 구좌읍 세화14길 3",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-2",
      "name": "가람",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 제주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 제주시 복지로북길 4",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-3",
      "name": "가람돌솥밥",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 중문관광로 332 (대포동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-4",
      "name": "가시식당",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 표선면 가시로565번길 24",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-5",
      "name": "가시아방국수",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 성산읍 섭지코지로 10",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-6",
      "name": "가시어멍김밥",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 제주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 제주시 월랑로 36",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-7",
      "name": "갈치공장",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 제주시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 제주시 해맞이해안로 1296",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-food-api-8",
      "name": "갈치왕",
      "type": "restaurant",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 맛집 — 사우나 전후 식사 코스",
      "tags": [
        "tourAPI",
        "맛집"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 일주서로 1146 (상예동)",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-1",
      "name": "가마오름",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 제주시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 제주시 한경면 청수리",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-2",
      "name": "가문이오름(감은이오름)",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 표선면 가시리",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-3",
      "name": "가새기오름",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 제주시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 제주시 오라삼동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-4",
      "name": "가세오름",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 표선면 녹산로 554",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-5",
      "name": "가시리국산화풍력발전단지",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 표선면 녹산로 464-78",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-6",
      "name": "가시오름",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 대정읍 하모이삼로21번길 1",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-7",
      "name": "각시바위오름",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 호근동",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    },
    {
      "id": "jeju-att-api-8",
      "name": "갈마못(갈뫼못)",
      "type": "attraction",
      "region": "jeju",
      "city": "제주특별자치도 서귀포시",
      "summary": "tourAPI 등록 볼거리 — 사우나 사이 완충 코스",
      "tags": [
        "tourAPI",
        "볼거리"
      ],
      "priceLevel": "mid",
      "avgDurationMin": 60,
      "highlights": [
        "제주특별자치도 서귀포시 표선면 성읍리",
        "현장 확인 권장"
      ],
      "source": "tourapi"
    }
  ]
};

// 수집 요약 (모니터링/디버그용)
export const enrichedSummary = [
  {
    "region": "seoul",
    "foodCount": 500,
    "attrCount": 445,
    "foodTitles": [
      "가나돈까스의집",
      "가담",
      "가막골흑염소요리전문점",
      "가문",
      "가산물갈비&백년불고기"
    ],
    "attrTitles": [
      "가회동성당",
      "갈산공원",
      "강남",
      "강남 마이스 관광특구",
      "강서습지생태공원"
    ]
  },
  {
    "region": "incheon",
    "foodCount": 371,
    "attrCount": 159,
    "foodTitles": [
      "가마솥손두부",
      "가연식당",
      "가온칼국수 송도본점",
      "가현산 잔치국수",
      "가회동샤브칼국수 송도컨벤시아점"
    ],
    "attrTitles": [
      "감중공원",
      "갑곶돈대",
      "갑곶순교성지",
      "강화 사기리 탱자나무",
      "강화 삼랑성"
    ]
  },
  {
    "region": "daejeon",
    "foodCount": 202,
    "attrCount": 82,
    "foodTitles": [
      "가나샤브샤브",
      "가남지",
      "가데나 레스토랑",
      "간사이",
      "갈마짬뽕"
    ],
    "attrTitles": [
      "갑천",
      "광수사",
      "국립대전숲체원",
      "국립대전현충원 보훈둘레길",
      "금강로하스 대청공원 (암석식물원)"
    ]
  },
  {
    "region": "daegu",
    "foodCount": 206,
    "attrCount": 204,
    "foodTitles": [
      "가야성",
      "가원식당",
      "가창닭갈비",
      "갈비만 대구본점",
      "감나무집"
    ],
    "attrTitles": [
      "가창 찐빵 골목",
      "감삼못공원",
      "강정고령보",
      "경극고택",
      "경상감영공원"
    ]
  },
  {
    "region": "gwangju",
    "foodCount": 87,
    "attrCount": 81,
    "foodTitles": [
      "가배당",
      "개마고원",
      "갤러리24",
      "계림동잔치집",
      "광후장어"
    ],
    "attrTitles": [
      "경암근린공원",
      "관덕정의 각궁",
      "광주 경찰충혼탑",
      "광주 송정동 떡갈비 골목",
      "광주 수완호수공원"
    ]
  },
  {
    "region": "busan",
    "foodCount": 350,
    "attrCount": 153,
    "foodTitles": [
      "가마솥생복집",
      "가야포차선지국",
      "가야할매 밀면",
      "감포참가자미",
      "강호중마라도물회"
    ],
    "attrTitles": [
      "가덕도 등대",
      "가덕도 연대봉",
      "가톨릭 특성화 거리",
      "감지해변",
      "감천사(부산)"
    ]
  },
  {
    "region": "gangwon",
    "foodCount": 500,
    "attrCount": 482,
    "foodTitles": [
      "가고파부치기",
      "가람집옹심이",
      "가리왕산가든",
      "가방속커피향기",
      "가보자순대국"
    ],
    "attrTitles": [
      "가람리조트",
      "가리왕산케이블카",
      "가원습지 생태자연공원",
      "간이해변",
      "간현관광지"
    ]
  },
  {
    "region": "gyeongju",
    "foodCount": 461,
    "attrCount": 483,
    "foodTitles": [
      "가마솥 양푼이 밥상",
      "가봉반과",
      "가정초밥 효자점",
      "갈치조림 토박이식당",
      "개운궁"
    ],
    "attrTitles": [
      "가래실문화마을(별별미술마을)",
      "가산수피아",
      "가오실공원",
      "감못(부지)",
      "감응사(성주)"
    ]
  },
  {
    "region": "jeju",
    "foodCount": 500,
    "attrCount": 349,
    "foodTitles": [
      "가는곶 세화",
      "가람",
      "가람돌솥밥",
      "가시식당",
      "가시아방국수"
    ],
    "attrTitles": [
      "가마오름",
      "가문이오름(감은이오름)",
      "가새기오름",
      "가세오름",
      "가시리국산화풍력발전단지"
    ]
  }
];
