// auto-generated by scripts/sync-tourapi.mjs — 2026-07-09T00:00:00.000Z
// 하이브리드: 사우나/온천=curated, 맛집/볼거리=tourAPI 보강.
// CI(주간)에서 갱신되어 커밋됩니다. 이 파일이 없으면 앱 빌드가 실패하므로 초기 커밋 포함.
export const enrichedPlaces: Record<string, any[]> = {};
export const enrichedSummary: any[] = [];
