// scripts/sync-tourapi.mjs를 모의 tourAPI 서버에 붙여 실제로 실행해 본다.
// 실제 키·실제 호출 없이 요청 파라미터와 생성 파일을 검증한다 (임시 폴더에 복사해서 실행).
import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { spawn } from "node:child_process";
import { createServer, type Server } from "node:http";
import { mkdtempSync, mkdirSync, copyFileSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { AddressInfo } from "node:net";
import { ALL_REGIONS } from "./schema";

type Item = { title: string; addr1: string; mapx?: string; mapy?: string };
const item = (title: string, addr1: string): Item => ({ title, addr1, mapx: "127.0", mapy: "37.5" });

// 요청 조건별 모의 응답
function respond(q: URLSearchParams): Item[] {
  const type = q.get("contentTypeId");
  if (q.get("lDongSignguCd") === "130") {
    // 경주: 숙소는 0건 → 기존 데이터 유지 경로. 나머지는 경주 + 조건을 벗어난 경산 1곳
    if (type === "32") return [];
    return [
      item(`경주-${type}-1`, "경상북도 경주시 태종로 1"),
      item(`경산-${type}-1`, "경상북도 경산시 중앙로 1"),
      item(`경주-${type}-2`, "경상북도 경주시 보문로 2"),
    ];
  }
  if (q.get("areaCode") === "1" && type === "39") {
    // 서울 맛집: 앞의 10곳이 전부 강남구 — 그대로 앞에서 8곳을 자르면 한 구에 몰린다
    return [
      ...Array.from({ length: 10 }, (_, i) => item(`강남-${i}`, `서울특별시 강남구 테헤란로 ${i}`)),
      item("마포-0", "서울특별시 마포구 양화로 1"),
      item("종로-0", "서울특별시 종로구 종로 1"),
    ];
  }
  const area = q.get("areaCode") ?? "?";
  return [item(`${area}-${type}-a`, "어느도 어느시 1"), item(`${area}-${type}-b`, "어느도 저느시 2")];
}

// 이전 동기화 결과: 경주에 상주 숙소가 섞여 있던 상태
const PREV = `// auto-generated by scripts/sync-tourapi.mjs — 2026-09-28T00:00:00.000Z
import type { Place } from "./schema";

export const enrichedPlaces: Record<string, Place[]> = ${JSON.stringify({
  gyeongju: [
    { id: "gyeongju-stay-api-1", name: "경주 숙소", type: "lodging", region: "gyeongju", city: "경상북도 경주시", address: "경상북도 경주시 보문로 1", summary: "", tags: [], priceLevel: "mid", avgDurationMin: 480, highlights: [] },
    { id: "gyeongju-stay-api-2", name: "상주 숙소", type: "lodging", region: "gyeongju", city: "경상북도 상주시", address: "경상북도 상주시 경상대로 1", summary: "", tags: [], priceLevel: "mid", avgDurationMin: 480, highlights: [] },
  ],
}, null, 2)};

// 수집 요약 (모니터링/디버그용)
export const enrichedSummary = [];
`;

let dir = "";
let server: Server;
const requests: URLSearchParams[] = [];
let places: Record<string, { name: string; city: string; type: string; sigungu?: string }[]> = {};
let status: { result: string; fresh: string; kept: string[] };

beforeAll(async () => {
  dir = mkdtempSync(join(tmpdir(), "sync-tourapi-"));
  mkdirSync(join(dir, "scripts"));
  mkdirSync(join(dir, "src", "data"), { recursive: true });
  copyFileSync(fileURLToPath(new URL("../../scripts/sync-tourapi.mjs", import.meta.url)), join(dir, "scripts", "sync-tourapi.mjs"));
  writeFileSync(join(dir, "src", "data", "seed.enriched.ts"), PREV);

  server = createServer((req, res) => {
    const q = new URL(req.url ?? "/", "http://mock").searchParams;
    requests.push(q);
    const items = respond(q);
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({
      response: {
        header: { resultCode: "0000", resultMsg: "OK" },
        body: { items: items.length ? { item: items } : "", numOfRows: 100, pageNo: 1, totalCount: items.length },
      },
    }));
  });
  await new Promise<void>((r) => server.listen(0, "127.0.0.1", r));
  const { port } = server.address() as AddressInfo;

  await new Promise<void>((done, fail) => {
    const child = spawn(process.execPath, [join(dir, "scripts", "sync-tourapi.mjs")], {
      env: { ...process.env, TOURAPI_KEY: "mock-key", TOURAPI_BASE: `http://127.0.0.1:${port}/svc`, GITHUB_OUTPUT: "" },
      stdio: "ignore",
    });
    child.on("error", fail);
    child.on("exit", (code) => (code === 0 ? done() : fail(new Error(`exit ${code}`))));
  });

  const out = readFileSync(join(dir, "src", "data", "seed.enriched.ts"), "utf8");
  places = JSON.parse(out.match(/export const enrichedPlaces[^=]*=\s*([\s\S]*?);\s*\/\/ 수집 요약/)![1]);
  status = JSON.parse(readFileSync(join(dir, "src", "data", "sync-status.json"), "utf8"));
}, 30_000);

afterAll(() => {
  server?.close();
  if (dir) rmSync(dir, { recursive: true, force: true });
});

describe("sync-tourapi — 모의 응답으로 실행", () => {
  test("앱의 18개 지역을 모두 동기화한다", () => {
    expect(Object.keys(places).sort()).toEqual([...ALL_REGIONS].sort());
    const areaCodes = new Set(requests.map((q) => q.get("areaCode")).filter(Boolean));
    expect(areaCodes.size).toBe(17);
  });

  test("경주는 경북 전체가 아니라 경주시만 조회하고, 섞여 온 다른 시군구는 버린다", () => {
    const gyeongjuReqs = requests.filter((q) => q.get("lDongSignguCd") === "130");
    expect(gyeongjuReqs.length).toBeGreaterThan(0);
    for (const q of gyeongjuReqs) {
      expect(q.get("lDongRegnCd")).toBe("47");
      expect(q.get("areaCode")).toBeNull();
    }
    expect(places.gyeongju.length).toBeGreaterThan(0);
    for (const p of places.gyeongju) expect(p.city).toBe("경상북도 경주시");
  });

  test("0건이라 기존 데이터를 유지할 때도 경주 밖 장소는 걸러낸다", () => {
    const stays = places.gyeongju.filter((p) => p.type === "lodging");
    expect(stays.map((p) => p.name)).toEqual(["경주 숙소"]);
    expect(status.kept).toContain("gyeongju:stay");
    expect(status.fresh).toBe("53/54");
  });

  test("가나다순 앞쪽이 아니라 최근 수정순으로 받고, 시군구를 번갈아 고른다", () => {
    for (const q of requests) expect(q.get("arrange")).toBe("C");
    const seoulFood = places.seoul.filter((p) => p.type === "restaurant");
    expect(seoulFood).toHaveLength(8);
    expect(new Set(seoulFood.map((p) => p.city))).toEqual(
      new Set(["서울특별시 강남구", "서울특별시 마포구", "서울특별시 종로구"])
    );
  });

  test("시군구 id는 쓰지 않는다 — seed.ts가 전국 목록으로 매핑한다", () => {
    for (const list of Object.values(places)) for (const p of list) expect(p.sigungu).toBeUndefined();
  });
});
